server:
  port: 8080

jwt:
  secret: "your_jwt_secret"

rate_limiting:
  redis_addr: "localhost:6379"
  request_limit: 100
  time_window: 60  # in seconds

routes:
  - path: /users
    service: users-service
    service_port: 50051
  - path: /orders
    service: orders-service
    service_port: 50052
  - path: /products
    service: products-service
    service_port: 50053
